# Generated by Django 2.0.7 on 2018-08-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('greeting', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'birthdays',
            },
        ),
    ]
